%\VignetteIndexEntry{Rendering all semiconductor bandgaps as a LaTeX table}
%\VignetteEngine{knitr::knitr}
%\VignetteKeyword{LaTeX}
%\VignetteKeyword{bandgaps}
%\VignetteKeyword{semiconductors}
%\VignetteKeyword{conduction band}
%\VignetteKeyword{valence band}
%\VignetteKeyword{dataset}
%\VignetteKeyword{photoelectrochemistry}


\documentclass[a4paper]{article}

% ----------------------------------------------------------------------
% Page layout
% ----------------------------------------------------------------------
\usepackage[%
   left=2.0cm,
   right=2.0cm,
   top=1.785cm,
   bottom=2.0cm]{geometry}
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Fonts and symbols
% ----------------------------------------------------------------------
% inputenc should be loaded before biblatex
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{textcomp} % \textdegree, \textmu, \texttrademark
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Bibliography
% ----------------------------------------------------------------------
\usepackage[%
   backend=biber,
   url=false,
   doi=true]{biblatex}
% add DOIs in reference list
\newcommand*\doiformat[1]{\small#1}
\DeclareFieldFormat{doi}{%
   \mkbibacro{\small{DOI}}\addcolon\space
   \ifhyperref{%
      \href{https://dx.doi.org/#1}{\doiformat{#1}}%
   }{%
      \doiformat{#1}%
   }%
}
\addbibresource{references.bib}
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Support packages - general
% ----------------------------------------------------------------------
\usepackage{gitinfo2}
% \usepackage{fancyhdr}
%    \pagestyle{fancy}
\usepackage{csquotes}
% used by setstretch{} later in the preamble
\usepackage{setspace}
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Support packages - graphics, captions, footnotes, etc.
% ----------------------------------------------------------------------
\usepackage{graphicx}
\usepackage[%
   format=plain,
   justification=justified,
   singlelinecheck=false,
   font={stretch=1.125,small},
   labelfont=bf,
   labelsep=space]{caption}
\usepackage{subcaption}
\usepackage{tikz}
% \usepackage{rotating} % rotate full-page floats
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Support packages - tables, lists
% ----------------------------------------------------------------------
\usepackage{booktabs}
\usepackage{longtable}
\usepackage[inline]{enumitem} % control layout of lists
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Support packages - chemistry, science
% ----------------------------------------------------------------------
\usepackage{amssymb} %\geqslant, %\leqslant
\usepackage{chemformula}
   \setchemformula{charge-style=math}
\usepackage{siunitx}
   \sisetup{%
      separate-uncertainty,
      detect-family,
      range-phrase=\ensuremath{\text{ to }}}
   \DeclareSIUnit{\counts}{cts}
   \DeclareSIUnit{\cps}{cps}
   \DeclareSIUnit{\molar}{\mole\per\cubic\deci\metre}
   \DeclareSIUnit{\Molar}{\textsc{m}}
   % electrochemical scales need to defined in two steps (siunitx v3 not behaving like v2 for some reason)
   \DeclareSIUnit{\vsAgCl}{vs~\ch{Ag}/\ch{AgCl}}
   \DeclareSIUnit{\vsNHE}{vs~NHE}
   \DeclareSIUnit{\vsSHE}{vs~SHE}
   \DeclareSIUnit{\vsSCE}{vs~SCE}
   \DeclareSIUnit{\voltAgCl}{\volt\vsAgCl}
   \DeclareSIUnit{\voltNHE}{\volt\vsNHE}
   \DeclareSIUnit{\voltSHE}{\volt\vsSHE}
   \DeclareSIUnit{\voltSCE}{\volt\vsSCE}
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% Packages that need to be called last: hyperref, cleveref etc.
% ----------------------------------------------------------------------
\usepackage[%
   pdfkeywords={Semiconductors Band gaps Conduction Band Valence Band Dataset Photoelectrochemistry},%
	pdfauthor={Taha Ahmed, Uppsala university},%
	pdftitle={Rendering all semiconductor bandgaps as a LaTeX table},%
	pdfsubject={Vignette},%
	pdftex]{hyperref}
\usepackage[nameinlink]{cleveref}
% ----------------------------------------------------------------------

\title{Rendering all semiconductor \texttt{bandgaps} as a \LaTeX\ table}
\date{\today}
\author{Taha Ahmed}


% ----------------------------------------------------------------------
% R SETUP
% ----------------------------------------------------------------------
<<'R-setup', echo=F, results='hide', cache=FALSE>>=
options(
   tikzDefaultEngine = "pdftex",
   "tikzLatexPackages" = c(
      "\\usepackage{tikz}\n",
      "\\usepackage[active,tightpage,psfixbb]{preview}\n",
      "\\PreviewEnvironment{pgfpicture}\n",
      "\\setlength\\PreviewBorder{0pt}\n",
      "\\usepackage{chemformula}\n",
      "\\setchemformula{charge-style=math}\n",
      "\\usepackage{siunitx}\n",
      "\\sisetup{separate-uncertainty,detect-family,range-phrase=\\ensuremath{\\text{ to }}}\n",
      "\\DeclareSIUnit{\\counts}{cts}\n",
      "\\DeclareSIUnit{\\cps}{cps}\n",
      "\\DeclareSIUnit{\\molar}{\\mole\\per\\cubic\\deci\\metre}\n",
      "\\DeclareSIUnit{\\Molar}{\\textsc{m}}\n",
      "\\DeclareSIUnit{\\vsAgCl}{vs~\\ch{Ag}/\\ch{AgCl}}",
      "\\DeclareSIUnit{\\vsNHE}{vs~NHE}",
      "\\DeclareSIUnit{\\vsSHE}{vs~SHE}",
      "\\DeclareSIUnit{\\vsSCE}{vs~SCE}",
      "\\DeclareSIUnit{\\voltAgCl}{\\volt\\vsAgCl}",
      "\\DeclareSIUnit{\\voltNHE}{\\volt\\vsNHE}",
      "\\DeclareSIUnit{\\voltSHE}{\\volt\\vsSHE}",
      "\\DeclareSIUnit{\\voltSCE}{\\volt\\vsSCE}"),
   digits   = 7,
   width    = 84,
   continue = "  ",
   prompt   = "> ",
   stringsAsFactors = FALSE)
# Was getting this confusing error during devtools:check() if library(here) was used (same for the other vignette).
# Only fixed by not using library(here) anymore (adding here::i_am() had no effect):
#    > checking re-building of vignette outputs ... WARNING
#   Error(s) in re-building vignettes:
#     ...
#   --- re-building ‘data.Rnw’ using knitr
#   here() starts at /media/bay/taha/chepec/chetex/common/R/bandgaps.Rcheck/vign_test/bandgaps
#   Quitting from lines 167-199 (data.Rnw)
#   Error: processing vignette 'data.Rnw' failed with diagnostics:
#   The 'path' is not in a git repository
#   --- failed re-building ‘data.Rnw’
# here::i_am("vignettes/data.Rnw")
@
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
% R LOAD PACKAGES
% ----------------------------------------------------------------------
<<'load-R-packages', echo=F, results='hide', message=FALSE>>=
library(bandgaps)
library(refelectrodes)
# packages listed below should also be listed in DESCRIPTION
# library(here)
library(common)
# library(git2r)
#    repo <- repository(here())
library(dplyr)
library(xtable)
library(knitr)
opts_knit$set(
   self.contained = FALSE,
   child.path = '')
opts_chunk$set(
   dev = 'tikz',
   # external = TRUE only takes effect when tikz is the ONLY dev option
   external = TRUE,
   cache = FALSE,
   fig.width = 3.40, # 2.60,
   # corresponding height based on golden ratio (1.618034):
   # W 3.54 ==> H 2.19 >> works better >> W 2.60, H 1.61
   # W 5.51 ==> H 3.41
   # W 7.48 ==> H 4.62 >> works better >> W 5.40, H 3.34
   fig.height = 2.10, # 1.61,
   out.width = '3.40in', # '2.60in',
   fig.align = 'center',
   # size affects all knitr output. We use it primarily
   # to match knitr font size to figure captions
   size = 'footnotesize',
   echo = FALSE,
   eval = TRUE,
   results = 'hide',
   message = FALSE,
   tidy = FALSE)
@
% ----------------------------------------------------------------------


\setlength\parindent{0pt}
\begin{document}
\maketitle

This package presents the position (potential) of the valence and conduction band edges
for semiconductors in contact with an aqueous electrolyte as an R dataframe.
The package was created mainly to make it easier to use and share this dataset
(which is entirely based on primary literature sources).
Apart from the included data, the package contains a number of auxiliary functions
meant to i) add new data, ii) tabulate the data, and iii) plot the band edges visually.

In this vignette we demonstrate how the included data (\texttt{bandgaps::semiconductors})
can be typeset using \LaTeX (see \cref{tab:semiconductors-asis}).
To make the rendered table look pretty, we will compress some columns and display
comments as tabular footnotes, but without removing any data from display.

<<'comments-to-footnotes'>>=
comments <- unique(semiconductors$comment)
# Count existing comments and remove empty comments
k <- 0
tmp.comments <- character()
for (j in 1:length(comments)) {
   if (comments[j] != "") {
      k <- k + 1
      tmp.comments[k] <- comments[j]
   }
}
# Reset comments
comments <- tmp.comments
# Find their original positions in the semiconductors dataframe
unique.comment.positions <- list()
for (j in 1:length(comments)) {
   unique.comment.positions[[j]] <- which(semiconductors$comment == comments[j])
}
## create footnotemarks
footnotemark <- rep.int(NA, dim(semiconductors)[1])
for (j in 1:length(unique.comment.positions)) {
   footnotemark[unique.comment.positions[[j]]] <- j
   # # replace footnotemark numbers with symbols
   # footnotesymbol <- c("\\ast", "\\dag", "\\ddag", "\\S", "\\P")
   # for (m in 1:max(footnotemark, na.rm = T)) {
   #    footnotemark[which(footnotemark == m)] <- footnotesymbol[m]
   # }
}
@

We will render the table using \texttt{xtable} (that chunk is shown at the end of this document).

<<'tab-semiconductors-asis', results='asis'>>=
xtab.semiconductors <-
   semiconductors %>%
   mutate(
      formula = ifelse(
         semiconductors$polymorph == "",
         paste0(
            ifelse(
               semiconductors$sctype == "",
               "",
               paste0("$", semiconductors$sctype, "$-")),
            "\\ch{", semiconductors$formula, "}"),
         paste0(
            ifelse(
               semiconductors$sctype == "",
               "",
               paste0("$", semiconductors$sctype, "$-")),
            "\\ch{", semiconductors$formula, "} ", "(", semiconductors$polymorph, ")"))) %>%
   mutate(
      pH = ifelse(
         is.na(semiconductors$pH),
         "\\multicolumn{1}{c}{\\texttt{NA}}",
         semiconductors$pH)) %>%
   mutate(
      pH.ZPC = ifelse(
         is.na(semiconductors$pH.ZPC),
         "\\multicolumn{1}{c}{\\texttt{NA}}",
         semiconductors$pH.ZPC)) %>%
   mutate(
      ref = ifelse(
         semiconductors$ref == "",
         "",
         paste0("\\cite{", semiconductors$ref, "}"))) %>%
   mutate(
      footnotemark = ifelse(
         is.na(footnotemark),
         "",
         paste0("$^{", footnotemark, "}$"))) %>%
   select(formula, class, CB, VB, Eg, pH, pH.ZPC, ref, footnotemark) %>%
   xtable()
caption(xtab.semiconductors) <- paste(
   "Band edge levels at the pH of ZPC for each material.",
   "All band edge potentials vs SHE at the given pH for each semiconductor.",
   "The point of zero surface charge for each material is given (where available)",
   "in the column labelled $\\mathrm{pH_{ZPC}}$.")
label(xtab.semiconductors) <- "tab:semiconductors-asis"
names(xtab.semiconductors) <- c(
   "{Formula}",
   "{Class}",
   "{$E_\\text{CB}$/\\si{\\voltSHE}}",
   "{$E_\\text{VB}$/\\si{\\voltSHE}}",
   "{$E_\\text{g}$/\\si{\\volt}}",
   "{pH}",
   "{pH$_\\text{ZPC}$}",
   "{Ref}",
   "{Note}")
digits(xtab.semiconductors) <- c(
   0, #row.names
   0, #formula
   0, #class
   2, #CB
   2, #VB
   2, #Eg
   2, #pH
   2, #pH.ZPC
   0, #Refs
   0) #Notes
display(xtab.semiconductors) <- c(
   "s", #row.names
   "s", #formula
   "s", #class
   "f", #CB
   "f", #VB
   "f", #Eg
   "f", #pH
   "f", #pH.ZPC
   "s", #Refs
   "s") #Notes
align(xtab.semiconductors) <- c(
   "l",                    #row.names
   "l",                    #formula
   "l",                    #class
   "S[table-format=+1.2]", #CB
   "S[table-format=+1.2]", #VB
   "S[table-format=+1.2]", #Eg
   "S[table-format=2.2]",  #pH
   "S[table-format=2.2]",  #pH.ZPC
   "c",                    #Refs
   "l")                    #Notes
## create-latex-footnotetexts
footnotetext <- comments
# add numbering to each footnote
for (j in 1:length(comments)) {
   footnotetext[j] <- paste0(
      "\\multicolumn{", dim(xtab.semiconductors)[2],
      "}{l}{", "$^{", j, "}$ ", comments[j], "}",
      ifelse(
         j == length(comments),
         "\n",
         "\\\\"))
}
print(
   xtab.semiconductors,
   floating = TRUE,
   floating.environment = "table",
   table.placement = "tbp",
   caption.placement = "top",
   hline.after = NULL,
   add.to.row = list(
      pos = list(
         -1,
         0,
         nrow(xtab.semiconductors),
         nrow(xtab.semiconductors)),
      command = c(
         "\\toprule\n",
         "\\midrule\n",
         "\\bottomrule\n",
         paste(footnotetext, collapse = "\n"))),
      include.rownames = FALSE,
      include.colnames = TRUE,
      type = "latex",
      tabular.environment = "tabular",
      latex.environments = c("center", "small"),
      # note: env small affects the table and footnotetext, but not the caption
      sanitize.text.function = function(x){x},
      math.style.negative = FALSE)
@


\section*{Nernstian pH dependence}

For many semiconductors in aqueous solutions, \ch{H+} and \ch{OH-} are the dominant
adsorbed species, and therefore the potential drop across the Helmholtz layer, $V_\text{H}$,
and the flatband potential changes systematically with pH.
The potential of zero $\zeta$ potential (PZZP, also known as the point of of zero charge, PZP)
is the pH at which the potential drop across the Helmoltz layer is zero \cite{Nozik1978}.
The change of $V_\text{H}$ with pH follows a straight-forward Nernstian relationship:
\begin{equation}\label{eq:nernstian-pH}
V_\text{H}/\si{\volt} = \SI{0.059}{\volt} (\text{pH}_\text{PZC} - \text{pH})
\end{equation}

I will assume that all oxides in this dataset obey this Nernstian pH dependence.
As for sulfides, literature reports are conflicted on the matter, \cite{Nozik1978,Xu2000}
so out of an abundance of caution we will treat all sulfides as non-Nernstian.
In some cases, individual non-oxide semiconductors have been shown to follow Nernstian pH behaviour.
To keep track of Nernstian (or not) behaviour for all semiconductors, we have added
a boolean variable \texttt{Nernstian} to the dataset (either \texttt{TRUE} or \texttt{FALSE}).


\printbibliography


\clearpage
\section*{\texttt{xtable} code chunk}

<<'print-tab-semiconductors-asis', ref.label='tab-semiconductors-asis', eval=FALSE, echo=TRUE>>=
@



\clearpage
%%%%% TikZ box displaying commit history, R session info, and LaTeX version info
\begin{tikzpicture}[remember picture, overlay]%
\node (gitbox) at (current page.north east)
   [xshift=-2cm, yshift=-2cm, text width=10cm, fill=blue!40, below left, font=\sffamily\small\color{white}]%
{\raggedright\bfseries%
Source: \texttt{\jobname.Rnw}\\%
git refs: \texttt{\gitReferences}\\%
git hash: \texttt{\gitHash}\\%
git author: \gitAuthorName\\%
author email: \gitAuthorEmail\\%
commit date: \gitAuthorIsoDate\\%
compile date: \Sexpr{Sys.time()}};%
\node (gitRbox) at (gitbox.south west) [yshift=0.35cm, text width=10cm, below right, font=\sffamily\small]%
{%
<<'gitR-info', echo=FALSE, results='markup', cache=FALSE>>=
# status(repo)
@
};%
\node (Rbox) at (gitRbox.south west) [fill=blue!20, text width=10cm, below right, font=\sffamily\small]%
{%
<<'R-session-info', echo=FALSE, results='asis', cache=FALSE>>=
toLatex(sessionInfo(), locale=F)
@
};%
\node (LaTeXbox) at (Rbox.south west) [yshift=-0.10cm, fill=blue!10, text width=10cm, below right, font=\sffamily\small]%
{%
<<'pdflatex-version', echo=FALSE, results='asis'>>=
latex.version.text <- system(command = "pdflatex -version", intern = TRUE)
# quick fixes: replace "\o" with "o", and remove all empty rows in latex.version.text
cat(paste0("\\noindent\n", paste(sub("\\\\o", "o", latex.version.text[which(latex.version.text != "")]), collapse = "\\\\\n")))
@
};%
\end{tikzpicture}%
%%%%%


\end{document}

